name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Build Angular App
      run: ng build --configuration production --aot
