name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - name: 'Deploy demo app using action'
      uses: ./
      with:
        run_lint: true
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: main
        base_href: https://mrizzello.github.io/isotope/
        deploy_branch: gh-pages 
        angular_dist_build_folder: isotope/dist/isotope
        angular_project_dir: isotope
